### ISSUE TITLE
User Authenthication

### ISSUE THREAD

**Issue by Buchimi** [UTDNebula/jupiter#124]
# Overview

I'm making this feature request because I saw a closed commit about authentication and @RubenOlano wanted to use Next Auth.

# Proposal

How about we use firebase auth instead?

**Comment by Jake3231** [comment]
Related: #99 #121

**Comment by RubenOlano** [comment]
I was talking to Caleb and Jason and they mentioned how they already use next-auth for planner and how it would make implementing other forms of auth easier

**Comment by nl32** [comment]
#121 added boilerplate for next-auth server side. However providers and a database aren't set up yet. I'm also not sure if there's any design that has been made for #109, though next auth does have a built in sign in page that could work until we design a page for sign in. We also need to consider where to but the login/logout buttons since that's not defined in the new design yet.
