### ISSUE TITLE
Create slide-out menu for navigation 

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#46]
# Overview

As a mobile user I should be able to access navigation options from a compact menu.

Currently, the navigation bar only displays information in a large-width context (desktop) though mobile users need a more optimized experience.

# Proposal
First, a new menu needs to be created showing identical navigation links to what is visible in the desktop mode. This could be a menu that slides from the right of the screen, or any other reasonable design.

**Comment by Jake3231** [comment]
Current behavior:

https://user-images.githubusercontent.com/13911970/196749163-aa5914ff-b7c9-4661-b0d9-30346305a6b4.mov

**Comment by gxanine** [comment]
Hi, 
I believe this has been already solved. 
When running the newest develop version, you get the full height slide-in menu on mobile as requested.

However, there's currently an issue with z-indexes, but it can be simply fixed by adding a high enough z-index to the `MobileNav`.

<img height="444" alt="image" src="https://user-images.githubusercontent.com/14282758/219949341-bef8245a-dc68-4983-b2ad-8b78b889adb4.png">


As for having the same links shared between desktop and mobile, I would take a different approach to generating links in general. Currently the links are duplicated, but it would easier, to simply create an array with link data, an then do a map over it. This would solve code duplication and make sure that there are always the same links in mobile and desktop navs.

I could take care of this issue :)

Sample:
```js
const navLinks = [
  {
    href: '/about',
    label: 'About',
  },
  {
    href: '/contact',
    label: 'Contact',
  },
];

function MobileNav() {
  return (
    <nav className="bg-red-500">
      {navLinks.map((link, index) => (
        <a key={index} href={link.href}>
          {link.label}
        </a>
      ))}
    </nav>
  );
}
function DesktopNav() {
  return (
    <nav className="bg-green-500">
      {navLinks.map((link, index) => (
        <a key={index} href={link.href}>
          {link.label}
        </a>
      ))}
    </nav>
  );
}
export function Navigation() {
  return (
    <div>
      <div className="block md:hidden">
        <MobileNav />
      </div>
      <div className="hidden md:block">
        <DesktopNav />
      </div>
    </div>
  );
}
    
```

**Comment by RubenOlano** [comment]
Currently outdates and requires new design

**Comment by gxanine** [comment]
Whooops! This issue got completely lost in my list... Sorry about that!
